server:
  servlet:
    context-path: /company
  port: 6080
spring:
  redis:
    cluster:
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: 192.168.86.202:7001,192.168.86.202:7002,192.168.86.202:7003,192.168.86.202:7004,192.168.86.202:7005,192.168.86.202:7006
  application:
    name: company-server
  datasource:
    url: jdbc:mysql://192.168.86.201:3306/huasj?useUnicode=true&characterEncoding=utf8
    username: root
    password: Cdb@123...
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
    thymeleaf:
      prefix: classpath:/templates/
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mappers/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka/eureka
